### ISSUE TITLE
SolutionPath in TesturaMutationBaseConfig.json full path

### ISSUE THREAD

**Issue by daanflore** [Testura/Testura.Mutation#20]
Hello,

I tested the plugin in VS after your post on redit and find it very usefull.
It helped me to find some untested logic in my code.

I noticed that the Solution path in the config.json file is a full path.
But I think it would be usefull if this could also work relative to the location of the config file.
This way you can check the file in and easily share it with your team.

**Comment by MilleBo** [comment]
Yeah that's a good point! Guess it's something I didn't think about when converting it from console to extension. Will fix it later tonight.

**Comment by MilleBo** [comment]
I made two changes to fix your issue: 

- We save solution path as null in config 
- We later on ignore solution path when creating mutations and instead use currently open solution path. 

I have updated the extension (to v1.1.0) with this change.

**Comment by daanflore** [comment]
I tested the new version of the extension and now it works if the solution path is equal to null
